// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using patyclub_server.Entities;

namespace patyclub_server.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220613115109_fix eventMst attribute name")]
    partial class fixeventMstattributename
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("patyclub_server.Entities.Achievement", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("describe")
                        .HasColumnType("text")
                        .HasColumnName("describe");

                    b.Property<int>("goal")
                        .HasColumnType("integer")
                        .HasColumnName("goal");

                    b.HasKey("id");

                    b.ToTable("ACHIEVEMENT");

                    b.HasData(
                        new
                        {
                            id = 1,
                            describe = "連續登入10天",
                            goal = 10
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.AutoCompleteList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("id");

                    b.ToTable("AUTO_COMPLETE_LIST");

                    b.HasData(
                        new
                        {
                            id = 1,
                            category = "K",
                            content = "patyclub"
                        },
                        new
                        {
                            id = 2,
                            category = "K",
                            content = "鳶嘴山"
                        },
                        new
                        {
                            id = 3,
                            category = "K",
                            content = "岩場"
                        },
                        new
                        {
                            id = 4,
                            category = "K",
                            content = "岩石"
                        },
                        new
                        {
                            id = 5,
                            category = "K",
                            content = "岩場地形"
                        },
                        new
                        {
                            id = 6,
                            category = "K",
                            content = "爬分"
                        },
                        new
                        {
                            id = 7,
                            category = "H",
                            content = "#ForFun"
                        },
                        new
                        {
                            id = 8,
                            category = "H",
                            content = "#積分"
                        },
                        new
                        {
                            id = 9,
                            category = "H",
                            content = "#中級山"
                        },
                        new
                        {
                            id = 10,
                            category = "H",
                            content = "#百岳"
                        },
                        new
                        {
                            id = 11,
                            category = "H",
                            content = "#遠足"
                        },
                        new
                        {
                            id = 12,
                            category = "H",
                            content = "#上山"
                        },
                        new
                        {
                            id = 13,
                            category = "H",
                            content = "#下海"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.ClientLog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("logCategory")
                        .HasColumnType("text")
                        .HasColumnName("logCategory");

                    b.Property<string>("logDate")
                        .HasColumnType("text")
                        .HasColumnName("logDate");

                    b.Property<string>("remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("stauts")
                        .HasColumnType("text")
                        .HasColumnName("stauts");

                    b.Property<string>("targetSeq")
                        .HasColumnType("text")
                        .HasColumnName("targetSeq");

                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.HasKey("id");

                    b.ToTable("CLIENT_LOG");

                    b.HasData(
                        new
                        {
                            id = 1,
                            logCategory = "eventTouch",
                            logDate = "2021/12/3 09:25:36",
                            targetSeq = "1",
                            userAccount = "adda"
                        },
                        new
                        {
                            id = 2,
                            logCategory = "eventTouch",
                            logDate = "2021/12/4 08:45:23",
                            targetSeq = "1",
                            userAccount = "adda"
                        },
                        new
                        {
                            id = 3,
                            logCategory = "eventTouch",
                            logDate = "2021/12/8 05:25:28",
                            targetSeq = "2",
                            userAccount = "adda"
                        },
                        new
                        {
                            id = 4,
                            logCategory = "eventTouch",
                            logDate = "2021/12/9 20:12:34",
                            targetSeq = "4",
                            userAccount = "yiyuan"
                        },
                        new
                        {
                            id = 5,
                            logCategory = "eventTouch",
                            logDate = "2021/12/5 23:53:14",
                            targetSeq = "1",
                            userAccount = "adda"
                        },
                        new
                        {
                            id = 6,
                            logCategory = "eventTouch",
                            logDate = "2021/12/7 10:01:02",
                            targetSeq = "3",
                            userAccount = "adda"
                        },
                        new
                        {
                            id = 7,
                            logCategory = "eventTouch",
                            logDate = "2021/12/5 01:42:51",
                            targetSeq = "2",
                            userAccount = "adda"
                        },
                        new
                        {
                            id = 8,
                            logCategory = "eventTouch",
                            logDate = "2021/12/5 13:12:44",
                            targetSeq = "3",
                            userAccount = "adda"
                        },
                        new
                        {
                            id = 9,
                            logCategory = "eventTouch",
                            logDate = "2021/12/1 15:32:12",
                            targetSeq = "1",
                            userAccount = "adda"
                        },
                        new
                        {
                            id = 10,
                            logCategory = "eventTouch",
                            logDate = "2021/12/2 18:42:31",
                            targetSeq = "3",
                            userAccount = "adda"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.EventAppendix", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("appendixPath")
                        .HasColumnType("text")
                        .HasColumnName("appendixPath");

                    b.Property<string>("category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("eventMstId")
                        .HasColumnType("integer")
                        .HasColumnName("eventMstId");

                    b.HasKey("id");

                    b.ToTable("EVENT_APPENDIX");

                    b.HasData(
                        new
                        {
                            id = 1,
                            appendixPath = "/Data/鳶嘴山.jpg",
                            category = "P",
                            eventMstId = 1
                        },
                        new
                        {
                            id = 2,
                            appendixPath = "/Data/APEX.jpg",
                            category = "P",
                            eventMstId = 6
                        },
                        new
                        {
                            id = 3,
                            appendixPath = "/Data/LOL.jpg",
                            category = "P",
                            eventMstId = 7
                        },
                        new
                        {
                            id = 4,
                            appendixPath = "/Data/嘉義｜阿里山生態文化之旅.jpg",
                            category = "P",
                            eventMstId = 8
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.EventAuditLog", b =>
                {
                    b.Property<int>("eventId")
                        .HasColumnType("integer")
                        .HasColumnName("eventId");

                    b.Property<int>("auditSeq")
                        .HasColumnType("integer")
                        .HasColumnName("auditSeq");

                    b.Property<string>("auditTarget")
                        .HasColumnType("text")
                        .HasColumnName("auditTarget");

                    b.Property<string>("auditMessage")
                        .HasColumnType("text")
                        .HasColumnName("auditMessage");

                    b.Property<string>("createdDate")
                        .HasColumnType("text")
                        .HasColumnName("createdDate");

                    b.HasKey("eventId", "auditSeq", "auditTarget");

                    b.ToTable("EVENT_AUDIT_LOG");

                    b.HasData(
                        new
                        {
                            eventId = 1,
                            auditSeq = 1,
                            auditTarget = "eventTitle",
                            auditMessage = "我是意見1",
                            createdDate = "2021/12/3 09:25:36"
                        },
                        new
                        {
                            eventId = 1,
                            auditSeq = 1,
                            auditTarget = "categoryId",
                            auditMessage = "我是意見2",
                            createdDate = "2021/12/3 09:22:36"
                        },
                        new
                        {
                            eventId = 1,
                            auditSeq = 1,
                            auditTarget = "eventStDate",
                            auditMessage = "我是意見3",
                            createdDate = "2021/12/3 09:21:36"
                        },
                        new
                        {
                            eventId = 1,
                            auditSeq = 1,
                            auditTarget = "eventIntroduction",
                            auditMessage = "我是意見4",
                            createdDate = "2021/12/3 09:26:36"
                        },
                        new
                        {
                            eventId = 1,
                            auditSeq = 1,
                            auditTarget = "cost",
                            auditMessage = "我是意見5",
                            createdDate = "2021/12/3 09:27:36"
                        },
                        new
                        {
                            eventId = 1,
                            auditSeq = 1,
                            auditTarget = "signUpStDate",
                            auditMessage = "我是意見6",
                            createdDate = "2021/12/3 09:28:36"
                        },
                        new
                        {
                            eventId = 1,
                            auditSeq = 2,
                            auditTarget = "eventTitle",
                            auditMessage = "我是意見11",
                            createdDate = "2021/12/4 09:23:36"
                        },
                        new
                        {
                            eventId = 1,
                            auditSeq = 2,
                            auditTarget = "eventAttention",
                            auditMessage = "我是意見22",
                            createdDate = "2021/12/4 09:22:36"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.EventCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("categoryName")
                        .HasColumnType("text")
                        .HasColumnName("categoryName");

                    b.Property<string>("enable")
                        .HasColumnType("text")
                        .HasColumnName("enable");

                    b.Property<int>("parentId")
                        .HasColumnType("integer")
                        .HasColumnName("parentId");

                    b.HasKey("id");

                    b.ToTable("EVENT_CATEGORY");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoryName = "測試活動A",
                            enable = "Y",
                            parentId = 0
                        },
                        new
                        {
                            id = 2,
                            categoryName = "測試活動B",
                            enable = "Y",
                            parentId = 0
                        },
                        new
                        {
                            id = 3,
                            categoryName = "測試活動A-1",
                            enable = "Y",
                            parentId = 1
                        },
                        new
                        {
                            id = 4,
                            categoryName = "測試活動A-2",
                            enable = "Y",
                            parentId = 1
                        },
                        new
                        {
                            id = 5,
                            categoryName = "測試活動A-3",
                            enable = "N",
                            parentId = 1
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.EventCollect", b =>
                {
                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.Property<int>("eventMstId")
                        .HasColumnType("integer")
                        .HasColumnName("eventMstId");

                    b.HasKey("userAccount", "eventMstId");

                    b.ToTable("EVENT_COLLECT");
                });

            modelBuilder.Entity("patyclub_server.Entities.EventMst", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ageLimit")
                        .HasColumnType("text")
                        .HasColumnName("ageLimit");

                    b.Property<int>("categoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryId");

                    b.Property<string>("cost")
                        .HasColumnType("text")
                        .HasColumnName("cost");

                    b.Property<string>("eventAttention")
                        .HasColumnType("text")
                        .HasColumnName("eventAttention");

                    b.Property<string>("eventCreateDate")
                        .HasColumnType("text")
                        .HasColumnName("eventCreateDate");

                    b.Property<string>("eventDetail")
                        .HasColumnType("text")
                        .HasColumnName("eventDetail");

                    b.Property<string>("eventEdDate")
                        .HasColumnType("text")
                        .HasColumnName("eventEdDate");

                    b.Property<string>("eventIntroduction")
                        .HasColumnType("text")
                        .HasColumnName("eventIntroduction");

                    b.Property<string>("eventStDate")
                        .HasColumnType("text")
                        .HasColumnName("eventStDate");

                    b.Property<string>("eventTitle")
                        .HasColumnType("text")
                        .HasColumnName("eventTitle");

                    b.Property<string>("examinationPassedDate")
                        .HasColumnType("text")
                        .HasColumnName("examinationPassedDate");

                    b.Property<int>("personLimit")
                        .HasColumnType("integer")
                        .HasColumnName("personLimit");

                    b.Property<string>("signUpEdDate")
                        .HasColumnType("text")
                        .HasColumnName("signUpEdDate");

                    b.Property<string>("signUpStDate")
                        .HasColumnType("text")
                        .HasColumnName("signUpStDate");

                    b.Property<string>("status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("id");

                    b.ToTable("EVENT_MST");

                    b.HasData(
                        new
                        {
                            id = 1,
                            categoryId = 3,
                            cost = "1000",
                            eventAttention = "【行前準備】\r\n\r\n1. 1500～2000cc 水\r\n\r\n2. 手套 （看個人非必要）有幾處需拉繩\r\n\r\n3. 穿登山鞋 或 較深紋路的鞋子\r\n\r\n4. 兩截式雨衣 （沒有的話就輕便雨衣）\r\n\r\n5. 長褲 （有彈性較佳）\r\n\r\n6. 身份證\r\n\r\n7. 午餐（麵包 or 御飯糰 之類）\r\n\r\n8. 帽子 （看個人非必要）\r\n\r\n9. 禦寒衣物\r\n\r\n10.小型後背包 \r\n\r\n11.一套乾淨衣服放車上回程如果有濕可換 \r\n\r\n12.衛生紙\r\n\r\n13.毛巾 （看個人非必要）",
                            eventCreateDate = "2021/12/05",
                            eventDetail = "日期：2021/03/20（六）\r\n天氣：晴☀️\r\n人數：阿寶、陳先生、毛毛，3人皆常爬山\r\n難度：中\r\n距離：全程2.1公里（27k上、27.3k下）\r\n時程：3小時45分\r\n07:45 27k登山口\r\n08:00 鳶嘴山/橫嶺山岔口\r\n08:25 二葉松涼亭\r\n09:10 鳶嘴山\r\n09:30 開始下山\r\n10:30 結束拉繩陡下\r\n10:45 稍來山/大雪山林道岔口\r\n11:30 27.3k登山口\r\n\r\n喝水800ml",
                            eventEdDate = "2021/12/31",
                            eventIntroduction = "號稱台中最美的中級山-鳶嘴山，是台中登山旅遊的熱門景點，位在台中東勢，海拔2180公尺，險峻的峭壁危崖吸引許多喜歡冒險的登山者挑戰。\r\n\r\n對於初次挑戰者困難度稍高，建議有登山經驗的帶領會比較安全一點，登頂後的美麗風景讓人覺得一切真的都值得，有機會的話真的要來造訪一次",
                            eventStDate = "2021/12/31",
                            eventTitle = "爬爬爬爬爬山趣",
                            examinationPassedDate = "2021/12/10",
                            personLimit = 10,
                            status = "TEMP",
                            tag = "S"
                        },
                        new
                        {
                            id = 2,
                            ageLimit = ">15",
                            categoryId = 3,
                            cost = "1000",
                            eventAttention = "",
                            eventCreateDate = "2021/12/05",
                            eventDetail = "",
                            eventEdDate = "2021/12/05",
                            eventIntroduction = "",
                            eventStDate = "2021/12/05",
                            eventTitle = "颱風天要幹嘛? 當然是去泛舟R!",
                            examinationPassedDate = "2021/12/05",
                            personLimit = 6,
                            status = "TEMP",
                            tag = "S"
                        },
                        new
                        {
                            id = 3,
                            ageLimit = ">6",
                            categoryId = 2,
                            cost = "1000",
                            eventAttention = "",
                            eventCreateDate = "2021/12/01",
                            eventDetail = "",
                            eventEdDate = "2021/12/17",
                            eventIntroduction = "",
                            eventStDate = "2021/12/15",
                            eventTitle = "SideProject Coding...",
                            examinationPassedDate = "2021/12/10",
                            personLimit = 8,
                            status = "TEMP",
                            tag = "S"
                        },
                        new
                        {
                            id = 4,
                            ageLimit = ">15",
                            categoryId = 1,
                            cost = "1000",
                            eventAttention = "",
                            eventCreateDate = "2021/12/05",
                            eventDetail = "",
                            eventEdDate = "2021/12/20",
                            eventIntroduction = "",
                            eventStDate = "2021/12/18",
                            eventTitle = "一日雙塔，騎起來~",
                            examinationPassedDate = "",
                            personLimit = 0,
                            status = "TEMP",
                            tag = "S"
                        },
                        new
                        {
                            id = 5,
                            ageLimit = ">18",
                            categoryId = 4,
                            cost = "1000",
                            eventAttention = "",
                            eventCreateDate = "2021/12/01",
                            eventDetail = "",
                            eventEdDate = "2021/12/20",
                            eventIntroduction = "",
                            eventStDate = "2021/12/20",
                            eventTitle = "JustDance跳跳跳!",
                            examinationPassedDate = "2021/12/10",
                            personLimit = 0,
                            status = "TEMP",
                            tag = "H"
                        },
                        new
                        {
                            id = 6,
                            categoryId = 4,
                            cost = "1000",
                            eventAttention = "雷包勿來",
                            eventCreateDate = "2021/12/02",
                            eventDetail = "今天晚上五點開打\r\n打到白金為止",
                            eventEdDate = "2021/12/16",
                            eventIntroduction = "銅牌一日上白金",
                            eventStDate = "2021/12/15",
                            eventTitle = "APEX 爬分",
                            examinationPassedDate = "",
                            personLimit = 0,
                            status = "TEMP",
                            tag = ""
                        },
                        new
                        {
                            id = 7,
                            categoryId = 4,
                            cost = "1000",
                            eventAttention = "for fun",
                            eventCreateDate = "2021/12/01",
                            eventDetail = "打到大家都累為止",
                            eventEdDate = "2021/12/26",
                            eventIntroduction = "如題",
                            eventStDate = "2021/12/25",
                            eventTitle = "LOL NG隨便打",
                            examinationPassedDate = "2021/12/20",
                            personLimit = 0,
                            status = "TEMP",
                            tag = ""
                        },
                        new
                        {
                            id = 8,
                            categoryId = 4,
                            cost = "1000",
                            eventAttention = "要帶夠錢錢\r\n要帶水\r\n要帶健保卡",
                            eventCreateDate = "2021/12/05",
                            eventDetail = "記得攜帶個人所需物品\r\n天冷注意保暖",
                            eventEdDate = "2021/12/5",
                            eventIntroduction = "阿里山鄉位於臺灣嘉義縣東部，北鄰南投縣竹山鎮，東鄰南投縣信義鄉、高雄市桃源區，西鄰梅山鄉、竹崎鄉、番路鄉，南接大埔鄉與高雄市那瑪夏區，是嘉義縣面積最大、人口密度最低的鄉鎮，其面積約佔全縣的1/5，也是嘉義縣唯一的山地鄉。",
                            eventStDate = "2021/12/2",
                            eventTitle = "阿里山郊遊趣",
                            examinationPassedDate = "",
                            personLimit = 0,
                            status = "TEMP",
                            tag = "S"
                        },
                        new
                        {
                            id = 9,
                            categoryId = 4,
                            cost = "1000",
                            eventAttention = "",
                            eventCreateDate = "2021/12/01",
                            eventDetail = "",
                            eventEdDate = "2021/12/8",
                            eventIntroduction = "",
                            eventStDate = "2021/12/3",
                            eventTitle = "不想想活動名-A4",
                            examinationPassedDate = "",
                            personLimit = 0,
                            status = "TEMP",
                            tag = ""
                        },
                        new
                        {
                            id = 10,
                            categoryId = 4,
                            cost = "1000",
                            eventAttention = "",
                            eventCreateDate = "2021/12/02",
                            eventDetail = "",
                            eventEdDate = "2021/12/5",
                            eventIntroduction = "",
                            eventStDate = "2021/12/5",
                            eventTitle = "不想想活動名-A5",
                            examinationPassedDate = "2021/12/2",
                            personLimit = 0,
                            status = "TEMP",
                            tag = ""
                        },
                        new
                        {
                            id = 11,
                            categoryId = 4,
                            cost = "1000",
                            eventAttention = "",
                            eventCreateDate = "2021/12/01",
                            eventDetail = "",
                            eventEdDate = "2021/12/9",
                            eventIntroduction = "",
                            eventStDate = "2021/12/9",
                            eventTitle = "不想想活動名-A6",
                            examinationPassedDate = "",
                            personLimit = 0,
                            status = "TEMP",
                            tag = "S"
                        },
                        new
                        {
                            id = 12,
                            categoryId = 4,
                            cost = "1000",
                            eventAttention = "",
                            eventCreateDate = "2021/12/02",
                            eventDetail = "",
                            eventEdDate = "2021/12/8",
                            eventIntroduction = "",
                            eventStDate = "2021/12/8",
                            eventTitle = "不想想活動名-A7",
                            examinationPassedDate = "",
                            personLimit = 0,
                            status = "TEMP",
                            tag = ""
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.EventPersonnel", b =>
                {
                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.Property<int>("eventMstId")
                        .HasColumnType("integer")
                        .HasColumnName("eventMstId");

                    b.Property<string>("permission")
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.Property<string>("status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("userAccount", "eventMstId", "permission");

                    b.ToTable("EVENT_PERSONNEL");

                    b.HasData(
                        new
                        {
                            userAccount = "adda",
                            eventMstId = 1,
                            permission = "OWNER",
                            status = "??"
                        },
                        new
                        {
                            userAccount = "yiyuan",
                            eventMstId = 1,
                            permission = "MEMBER",
                            status = "??"
                        },
                        new
                        {
                            userAccount = "peng",
                            eventMstId = 1,
                            permission = "MEMBER",
                            status = "??"
                        },
                        new
                        {
                            userAccount = "yiyuan",
                            eventMstId = 2,
                            permission = "OWNER",
                            status = "??"
                        },
                        new
                        {
                            userAccount = "peng",
                            eventMstId = 2,
                            permission = "MEMBER",
                            status = "??"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.MappingEventTag", b =>
                {
                    b.Property<int>("eventMstId")
                        .HasColumnType("integer")
                        .HasColumnName("eventMstId");

                    b.Property<int>("tagId")
                        .HasColumnType("integer")
                        .HasColumnName("tagId");

                    b.HasKey("eventMstId", "tagId");

                    b.ToTable("MAPPING_EVENT_TAG");
                });

            modelBuilder.Entity("patyclub_server.Entities.MappingPermissionRole", b =>
                {
                    b.Property<int>("permissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permissionId");

                    b.Property<int>("roleId")
                        .HasColumnType("integer")
                        .HasColumnName("roleId");

                    b.HasKey("permissionId", "roleId");

                    b.ToTable("MAPPING_PERMISSION_ROLE");

                    b.HasData(
                        new
                        {
                            permissionId = 1,
                            roleId = 1
                        },
                        new
                        {
                            permissionId = 2,
                            roleId = 2
                        },
                        new
                        {
                            permissionId = 3,
                            roleId = 2
                        },
                        new
                        {
                            permissionId = 4,
                            roleId = 2
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.MappingUserAchievement", b =>
                {
                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.Property<int>("achievementId")
                        .HasColumnType("integer")
                        .HasColumnName("achievementId");

                    b.Property<string>("currentProgress")
                        .HasColumnType("text")
                        .HasColumnName("currentProgress");

                    b.HasKey("userAccount", "achievementId");

                    b.ToTable("MAPPING_USER_ACHIEVEMENT");
                });

            modelBuilder.Entity("patyclub_server.Entities.MappingUserPersonalSetting", b =>
                {
                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.Property<int>("personalSettingId")
                        .HasColumnType("integer")
                        .HasColumnName("personalSettingId");

                    b.Property<string>("settingValue")
                        .HasColumnType("text")
                        .HasColumnName("settingValue");

                    b.HasKey("userAccount", "personalSettingId");

                    b.ToTable("MAPPING_USER_PERSONAL_SETTING");
                });

            modelBuilder.Entity("patyclub_server.Entities.MappingUserRole", b =>
                {
                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.Property<int>("roleId")
                        .HasColumnType("integer")
                        .HasColumnName("roleId");

                    b.HasKey("userAccount", "roleId");

                    b.ToTable("MAPPING_USER_ROLE");

                    b.HasData(
                        new
                        {
                            userAccount = "adda",
                            roleId = 1
                        },
                        new
                        {
                            userAccount = "admin",
                            roleId = 1
                        },
                        new
                        {
                            userAccount = "yiyuan",
                            roleId = 2
                        },
                        new
                        {
                            userAccount = "pang",
                            roleId = 2
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.News", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<string>("createdDate")
                        .HasColumnType("text")
                        .HasColumnName("createdDate");

                    b.Property<string>("lastUpdateDate")
                        .HasColumnType("text")
                        .HasColumnName("lastUpdateDate");

                    b.Property<string>("status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("tag")
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<string>("title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("id");

                    b.ToTable("NEWS");
                });

            modelBuilder.Entity("patyclub_server.Entities.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("actionCategory")
                        .HasColumnType("text")
                        .HasColumnName("actionCategory");

                    b.Property<string>("functionName")
                        .HasColumnType("text")
                        .HasColumnName("functionName");

                    b.HasKey("id");

                    b.ToTable("PERMISSION");

                    b.HasData(
                        new
                        {
                            id = 1,
                            actionCategory = "所有的權限",
                            functionName = "總管理"
                        },
                        new
                        {
                            id = 2,
                            actionCategory = "新增",
                            functionName = "活動管理"
                        },
                        new
                        {
                            id = 3,
                            actionCategory = "編輯",
                            functionName = "活動管理"
                        },
                        new
                        {
                            id = 4,
                            actionCategory = "刪除",
                            functionName = "活動管理"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.PersonalSetting", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.HasKey("id");

                    b.ToTable("PERSONAL_SETTING");
                });

            modelBuilder.Entity("patyclub_server.Entities.RegistrationForm", b =>
                {
                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.Property<int>("eventMstId")
                        .HasColumnType("integer")
                        .HasColumnName("eventMstId");

                    b.Property<int>("questionId")
                        .HasColumnType("integer")
                        .HasColumnName("questionId");

                    b.Property<string>("content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("userAccount", "eventMstId", "questionId");

                    b.ToTable("REGISTRATION_FORM");
                });

            modelBuilder.Entity("patyclub_server.Entities.RegistrationFormQuestion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EventMstId")
                        .HasColumnType("integer")
                        .HasColumnName("EventMstId");

                    b.Property<string>("category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("id");

                    b.ToTable("REGISTRATION_FORM_QUESTION");
                });

            modelBuilder.Entity("patyclub_server.Entities.RegistrationFormQuestionOption", b =>
                {
                    b.Property<int>("questionId")
                        .HasColumnType("integer")
                        .HasColumnName("questionId");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.HasKey("questionId", "id");

                    b.ToTable("REGISTRATION_FORM_QUESTION_OPTION");
                });

            modelBuilder.Entity("patyclub_server.Entities.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.ToTable("ROLE");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "系統管理員"
                        },
                        new
                        {
                            id = 2,
                            name = "一般使用者"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.SysCodeDtl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("codeDesc")
                        .HasColumnType("text")
                        .HasColumnName("codeDesc");

                    b.Property<string>("codeName")
                        .HasColumnType("text")
                        .HasColumnName("codeName");

                    b.Property<int>("orderSeq")
                        .HasColumnType("integer")
                        .HasColumnName("orderSeq");

                    b.Property<string>("sysCodeMstKeyword")
                        .HasColumnType("text")
                        .HasColumnName("sysCodeMstKeyword");

                    b.HasKey("id");

                    b.ToTable("SYS_CODE_DTL");

                    b.HasData(
                        new
                        {
                            id = 1,
                            codeDesc = "熱門活動",
                            codeName = "H",
                            orderSeq = 0,
                            sysCodeMstKeyword = "eventTag"
                        },
                        new
                        {
                            id = 2,
                            codeDesc = "精選活動",
                            codeName = "S",
                            orderSeq = 0,
                            sysCodeMstKeyword = "eventTag"
                        },
                        new
                        {
                            id = 3,
                            codeDesc = "暫存中",
                            codeName = "TEMP",
                            orderSeq = 1,
                            sysCodeMstKeyword = "eventStatus"
                        },
                        new
                        {
                            id = 4,
                            codeDesc = "已完成未送審",
                            codeName = "COMPLETE",
                            orderSeq = 2,
                            sysCodeMstKeyword = "eventStatus"
                        },
                        new
                        {
                            id = 5,
                            codeDesc = "已刪除",
                            codeName = "DELETE",
                            orderSeq = 5,
                            sysCodeMstKeyword = "eventStatus"
                        },
                        new
                        {
                            id = 6,
                            codeDesc = "擁有者",
                            codeName = "OWNER",
                            orderSeq = 1,
                            sysCodeMstKeyword = "eventPersonnel"
                        },
                        new
                        {
                            id = 7,
                            codeDesc = "成員",
                            codeName = "MEMBER",
                            orderSeq = 2,
                            sysCodeMstKeyword = "eventPersonnel"
                        },
                        new
                        {
                            id = 8,
                            codeDesc = "6-",
                            codeName = "<6",
                            orderSeq = 1,
                            sysCodeMstKeyword = "ageLimit"
                        },
                        new
                        {
                            id = 9,
                            codeDesc = "6+",
                            codeName = ">6",
                            orderSeq = 2,
                            sysCodeMstKeyword = "ageLimit"
                        },
                        new
                        {
                            id = 10,
                            codeDesc = "15+",
                            codeName = ">15",
                            orderSeq = 3,
                            sysCodeMstKeyword = "ageLimit"
                        },
                        new
                        {
                            id = 11,
                            codeDesc = "18+",
                            codeName = ">18",
                            orderSeq = 4,
                            sysCodeMstKeyword = "ageLimit"
                        },
                        new
                        {
                            id = 12,
                            codeDesc = "送審中",
                            codeName = "AUDIT",
                            orderSeq = 3,
                            sysCodeMstKeyword = "eventStatus"
                        },
                        new
                        {
                            id = 13,
                            codeDesc = "審核通過",
                            codeName = "AUDIT_PASS",
                            orderSeq = 4,
                            sysCodeMstKeyword = "eventStatus"
                        },
                        new
                        {
                            id = 14,
                            codeDesc = "關注者",
                            codeName = "WATCHER",
                            orderSeq = 3,
                            sysCodeMstKeyword = "eventPersonnel"
                        },
                        new
                        {
                            id = 15,
                            codeDesc = "退件",
                            codeName = "AUDIT_REJECT",
                            orderSeq = 4,
                            sysCodeMstKeyword = "eventStatus"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.SysCodeMst", b =>
                {
                    b.Property<string>("keyword")
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.Property<string>("name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.HasKey("keyword");

                    b.ToTable("SYS_CODE_MST");

                    b.HasData(
                        new
                        {
                            keyword = "eventTag",
                            name = "活動標記代碼",
                            remark = ""
                        },
                        new
                        {
                            keyword = "eventStatus",
                            name = "活動狀態代碼",
                            remark = ""
                        },
                        new
                        {
                            keyword = "eventPersonnel",
                            name = "活動人員身分別",
                            remark = ""
                        },
                        new
                        {
                            keyword = "ageLimit",
                            name = "年齡限制分級",
                            remark = ""
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.TagList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("tagName")
                        .HasColumnType("text")
                        .HasColumnName("tagName");

                    b.HasKey("id");

                    b.ToTable("TAG_LIST");
                });

            modelBuilder.Entity("patyclub_server.Entities.User", b =>
                {
                    b.Property<string>("account")
                        .HasColumnType("text")
                        .HasColumnName("account");

                    b.Property<string>("accountStatus")
                        .HasColumnType("text")
                        .HasColumnName("accountStatus");

                    b.Property<string>("activeState")
                        .HasColumnType("text")
                        .HasColumnName("activeState");

                    b.Property<string>("birthday")
                        .HasColumnType("text")
                        .HasColumnName("birthday");

                    b.Property<string>("city")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("emotionalState")
                        .HasColumnType("text")
                        .HasColumnName("emotionalState");

                    b.Property<string>("forgetPwdToken")
                        .HasColumnType("text")
                        .HasColumnName("forgetPwdToken");

                    b.Property<string>("forgetPwdTokenCreatedDate")
                        .HasColumnType("text")
                        .HasColumnName("forgetPwdTokenCreatedDate");

                    b.Property<string>("introduction")
                        .HasColumnType("text")
                        .HasColumnName("introduction");

                    b.Property<string>("name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("nickName")
                        .HasColumnType("text")
                        .HasColumnName("nickName");

                    b.Property<string>("password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.HasKey("account");

                    b.ToTable("USER");

                    b.HasData(
                        new
                        {
                            account = "adda",
                            accountStatus = "Active",
                            name = "阿達",
                            password = "adda"
                        },
                        new
                        {
                            account = "admin",
                            accountStatus = "Active",
                            email = "patyclub9453@gmail.com",
                            name = "阿管",
                            password = "admin"
                        },
                        new
                        {
                            account = "yiyuan",
                            accountStatus = "Active",
                            email = "charles01270@gmail.com",
                            name = "阿摳",
                            password = "yiyuan"
                        },
                        new
                        {
                            account = "pang",
                            accountStatus = "Active",
                            email = "cxz0917001997@gmail.com",
                            name = "阿彭",
                            password = "pang"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.UserAppendix", b =>
                {
                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("appendixPath")
                        .HasColumnType("text")
                        .HasColumnName("appendixPath");

                    b.Property<string>("category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.HasKey("userAccount", "id");

                    b.ToTable("USER_APPENDIX");

                    b.HasData(
                        new
                        {
                            userAccount = "yiyuan",
                            id = 1,
                            appendixPath = "/Data/0.jpg",
                            category = "H"
                        });
                });

            modelBuilder.Entity("patyclub_server.Entities.UserNotify", b =>
                {
                    b.Property<string>("userAccount")
                        .HasColumnType("text")
                        .HasColumnName("userAccount");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("userAccount", "id");

                    b.ToTable("USER_NOTIFY");
                });
#pragma warning restore 612, 618
        }
    }
}
